//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAWebApplication.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BannerMaster
    {
        public int BannerID { get; set; }
        public string BannerHeader { get; set; }
        public string BannerText { get; set; }
        public string BannerImagesPath { get; set; }
        public string Description { get; set; }
        public int BannerSequence { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    }
}
