//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAWebApplication.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_NewsSubCategoryMasters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_NewsSubCategoryMasters()
        {
            this.T_News_Masters = new HashSet<T_News_Masters>();
        }
    
        public int NewsSubCategoryID { get; set; }
        public int NewsCategory { get; set; }
        public string SubCategory { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_NewsCategoryMaster M_NewsCategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_News_Masters> T_News_Masters { get; set; }
    }
}
