//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAWebApplication.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RSADBEntities : DbContext
    {
        public RSADBEntities()
            : base("name=RSADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<M_NewsCategoryMaster> M_NewsCategoryMaster { get; set; }
        public virtual DbSet<M_NewsSubCategoryMasters> M_NewsSubCategoryMasters { get; set; }
        public virtual DbSet<M_RSAMasters> M_RSAMasters { get; set; }
        public virtual DbSet<T_News_Masters> T_News_Masters { get; set; }
        public virtual DbSet<M_BannerMaster> M_BannerMaster { get; set; }
    }
}
