//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAWebApplication.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_News_Masters
    {
        public int NewsID { get; set; }
        public int NewsType { get; set; }
        public int NewsSubCategoryID { get; set; }
        public string NewsHeading { get; set; }
        public string SubHeading { get; set; }
        public string Para1 { get; set; }
        public string Para2 { get; set; }
        public string Para3 { get; set; }
        public string Para4 { get; set; }
        public string Para5 { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string Img4 { get; set; }
        public string Img5 { get; set; }
        public string Remarks { get; set; }
        public string Location { get; set; }
        public int NoOfNewsViews { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_NewsSubCategoryMasters M_NewsSubCategoryMasters { get; set; }
        public virtual M_RSAMasters M_RSAMasters { get; set; }
    }
}
