//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSA.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RSA_YatraDBEntities : DbContext
    {
        public RSA_YatraDBEntities()
            : base("name=RSA_YatraDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_NewsCategoryMaster> M_NewsCategoryMaster { get; set; }
        public virtual DbSet<M_NewsSubCategoryMasters> M_NewsSubCategoryMasters { get; set; }
        public virtual DbSet<M_RSAMasters> M_RSAMasters { get; set; }
        public virtual DbSet<T_News_Masters> T_News_Masters { get; set; }
    }
}
